# Generated by Django 2.2 on 2020-03-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0004_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latlng',
            field=models.CharField(default='00.0000, 00.0000', max_length=50),
        ),
    ]
