# Generated by Django 2.2 on 2020-03-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0007_location_type_of_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type_of_location',
            field=models.CharField(choices=[('CS', 'Coastal'), ('RA', 'Raised'), ('FS', 'Forest'), ('PA', 'Park'), ('UB', 'Urban'), ('IO', 'Indoor and Oudoor'), ('SI', 'Semi Indoor')], default='PA', max_length=2),
        ),
    ]
