# Generated by Django 2.2 on 2020-03-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0008_auto_20200315_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type_of_excercise',
            field=models.CharField(choices=[('CT', 'Calisthenics'), ('FW', 'Freeweights'), ('MC', 'Mechanisms'), ('TF', 'Track & Field'), ('PS', 'Popular for Sports'), ('ES', 'Extreme Sports')], default='CT', max_length=2),
        ),
    ]
