# Generated by Django 2.2 on 2020-03-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0009_location_type_of_excercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(default='A short description about the atmosphere and surroundings of the location.', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='type_of_excercise',
            field=models.CharField(choices=[('CT', 'Calisthenics'), ('FW', 'Freeweights'), ('MC', 'Mechanisms'), ('TF', 'Track & Field'), ('PS', 'Popular for Sports'), ('ES', 'Extreme Sports'), ('SD', 'Self Defence'), ('LP', 'Larping (Live Action Role Playing')], default='CT', max_length=2),
        ),
    ]
