# Generated by Django 2.2 on 2020-03-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0010_auto_20200315_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='equipment',
            field=models.CharField(default='Unfinished- needs different model', max_length=200),
        ),
    ]
