# Generated by Django 2.2 on 2020-03-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0012_auto_20200315_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lon',
        ),
        migrations.AddField(
            model_name='location',
            name='location_images',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type_of_excercise',
            field=models.CharField(choices=[('Calisthenics', 'Calisthenics'), ('Free Weights', 'Freeweights'), ('Mechanisms', 'Mechanisms'), ('Track & Field', 'Track & Field'), ('Popular for Sports', 'Popular for Sports'), ('Extreme Sports', 'Extreme Sports'), ('Self Defence', 'Self Defence'), ('Larping', 'Larping (Live Action Role Playing')], default='Calisthenics', max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='type_of_location',
            field=models.CharField(choices=[('Coastal', 'Coastal'), ('Raised', 'Raised'), ('Forest', 'Forest'), ('Park', 'Park'), ('Urban', 'Urban'), ('Indoor and Outdoor', 'Indoor and Oudoor'), ('Shaded', 'Shaded')], default='Park', max_length=30),
        ),
    ]
