# Generated by Django 2.2 on 2020-03-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0014_auto_20200318_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='docfile',
        ),
        migrations.AddField(
            model_name='location',
            name='images',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder'),
        ),
    ]
