# Generated by Django 2.2 on 2020-03-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0016_auto_20200319_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='file',
            new_name='image',
        ),
    ]
