# Generated by Django 2.2 on 2020-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0021_auto_20200325_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='desc',
            field=models.CharField(default='A great and noble faction', max_length=10000),
        ),
    ]
