# Generated by Django 2.2 on 2020-03-25 11:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0022_auto_20200325_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
