# Generated by Django 2.2 on 2020-03-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0023_faction_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='image',
            field=models.ImageField(default='static/images/no-img.jpg', upload_to='static/images/'),
        ),
    ]
