# Generated by Django 3.0.4 on 2020-04-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0024_faction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_image',
            field=models.ImageField(blank=True, default='location_images/stock.png', null=True, upload_to='location_images/'),
        ),
    ]
