# Generated by Django 2.2.8 on 2020-05-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0027_auto_20200421_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='file',
            field=models.FileField(default=1, upload_to='attachments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(default='/pic_folder/None/no-img.jpg', upload_to='pic_folder', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='upload')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete='PROTECT', related_name='images', to='outdoorx.Location')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
