# Generated by Django 2.2.8 on 2020-05-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0031_location_multiimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic_folder', verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(default='stock.png', null=True, upload_to='pic_folder'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='images',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='outdoorx.Location'),
        ),
    ]
