# Generated by Django 2.2.8 on 2020-05-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0035_auto_20200520_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='me'),
        ),
    ]
