# Generated by Django 2.2.8 on 2020-05-20 07:39

from django.db import migrations, models
import outdoorx.models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0036_auto_20200520_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=outdoorx.models.images_directory_path),
        ),
    ]
