# Generated by Django 2.2.8 on 2020-05-26 09:46

from django.db import migrations, models
import outdoorx.models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0038_auto_20200525_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, upload_to=outdoorx.models.images_directory_path),
        ),
    ]
