# Generated by Django 2.2.8 on 2020-05-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0039_auto_20200526_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geotitle',
            field=models.CharField(default='OutdoorEx Location', max_length=100),
        ),
    ]
