# Generated by Django 2.2.8 on 2020-06-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0040_location_geotitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(default='A short description about the location', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=55, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=55, null=True),
        ),
    ]
