# Generated by Django 2.2.8 on 2020-06-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0042_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='location',
        ),
    ]
