# Generated by Django 2.2.8 on 2020-07-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0046_auto_20200715_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
