# Generated by Django 2.2.8 on 2020-07-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorx', '0047_auto_20200715_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
